import Head from "next/head";
import { Typography } from "@mui/material";

export default function Playlists() {
  return (
    <>
      <Head>
        <title>Maroon. Playlists</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography>Playlists</Typography>
    </>
  );
}
