import Head from "next/head";
import { Box, Typography, Button, Stack } from "@mui/material";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session, status } = useSession();
  if (status === "unauthenticated" || !session) {
    return (
      <>
        <Head>
          <title>Maroon.</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box
          sx={{
            position: "absolute",
            left: "50%",
            top: "50%",
            transform: "translate(-50%,-50%)",
            width: "80%",
            maxWidth: "600px",
          }}
        >
          <Typography fontSize={25} marginBottom="5rem" component="p">
            Maroon. is a free music streaming service powered by an adventagous
            full-stack framework by Vercel, based on the amazing React frontend
            framework; Next.js!
          </Typography>
        </Box>
      </>
    );
  }
  if (status === "loading") {
    return (
      <Box
        sx={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: "translate(-50%,-50%)",
        }}
      >
        <Typography component="p">Loading</Typography>
      </Box>
    );
  } else {
    return (
      <Stack
        direction="column"
        spacing={1}
        sx={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: "translate(-50%,-50%)",
          width: "100%",
          maxWidth: "300px",
        }}
      >
        <Typography
          component="p"
          fontWeight={700}
          variant="h5"
          textAlign="center"
        >
          Welcome, {session.user.name.split(" ")[0]}!
        </Typography>
        <Typography
          component="p"
          fontWeight={400}
          variant="body2"
          textAlign="justify"
        >
          This is one of my first React projects which uses Next.js for full
          backend functionality. I hope you enjoy it. You can wander around the
          webapp using the bottom navigation below! Have fun!
        </Typography>
        <Button variant="outlined" sx={{ width: "100%", padding: ".5rem" }}>
          Check out the Github Repo
        </Button>
      </Stack>
    );
  }
}
