import Head from "next/head";
import { TextField } from "@mui/material";
import { useState } from "react";

export default function Search() {
  const [query, setQuery] = useState("");
  return (
    <div style={{ position: "relative" }}>
      <Head>
        <title>Maroon. Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TextField
        variant="outlined"
        placeholder="Search"
        autoFocus
        sx={{
          width: "100%",
          maxWidth: "672px",
          position: "relative",
          margin: "0 auto",
        }}
        onChange={(event) => {
          setQuery(event.target.value);
        }}
      />
    </div>
  );
}
