import Head from "next/head";
import { Typography } from "@mui/material";
import { NavigationBarAuthed as Navbar } from "@/components/NavigationBar";

export default function Panel() {
  return (
    <>
      <Head>
        <title>Maroon. Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </>
  );
}
